on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ftp.codestudio.one
        username: vscodelogin@codestudio.one
        password: ${{ secrets.ftp_password }}
        server-dir: /
        protcol: sftp
        exclude: |
          **/.git*
          **/.git*/**
